name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v7

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar aplicación
        run: dotnet build --no-restore --configuration Release
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Descargar código
        uses: actions/checkout@v7

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Ejecutar tests
        run: dotnet test --no-restore --configuration Release
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Descargar código
        uses: actions/checkout@v5

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Instalar herramientas Lambda
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Generar artefacto Lambda
        run: dotnet lambda package --project-location SaludaApp --configuration Release --output-package publish/saluda-app.zip

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve